spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hateoas_db?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: "root"
    password: "Aleksandar99"
    continueOnError: true
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    hikari:
      connection-test-query: SELECT 1

  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
server:
  port: 8000